# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build and Test with Gradle

on:  [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      name: Git Checkout
      
    - name: Java installieren
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Build Gradle
      run: ./gradlew build
      
    - name: new release Gradle
      run: ./gradlew test
      
    - name: Unit tests results
      uses: actions/upload-artifact@v1
      with:
          name: unit-tests-results
          path: app/build/reports/tests/testDebugUnitTest/index.html
